name: Build JMComic APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
          pip install buildozer

      - name: Build APK
        run: |
          cd jmcomic_kivy
          buildozer android debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: JMComic-APK
          path: jmcomic_kivy/bin/*.apk
